import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/themes/theme-provider";
import { Toaster } from "sonner";
import { AuthInitProvider } from "@/features/auth/providers/authInit.provider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-sans",
});

const khmerFont = Kantumruy_Pro({
  subsets: ["khmer"],
  weight: ["400", "500", "700"],
  variable: "--font-khmer",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        roboto.variable,
        khmerFont.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col bg-gray-500">
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
        {/* </ThemeProvider> */}
        <AuthInitProvider>{children}</AuthInitProvider>
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
